services:
  app:
    container_name: micum
    image: micum:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/MICUM.py:/app/MICUM.py
      - ./input:/input
      - ./output:/output
    stdin_open: true
    tty: true